import Notification from '../../models/common/Notification.js';
import Notice from '../../models/common/Notice.js';
import Ticket from '../../models/common/Ticket.js';
import StaffLeave from '../../models/HRM/Staffleave.model.js';
import StudentLeave from '../../models/academic/StudentLeave.model.js';
import Exam from '../../models/academic/exam.model.js';
import AdmissionRequest from '../../models/school/admissionRequest.js';
import mongoose from 'mongoose';

/**
 * @desc    Get admin notifications, dynamically syncing from database sources
 * @route   GET /api/admin/notifications
 * @access  Private (Admin)
 */
export const syncAndGetAdminNotifications = async (req, res) => {
    try {
        const userId = req.user._id;
        const schoolId = req.user.school?._id || req.user.school;

        if (!schoolId) {
            return res.status(400).json({ success: false, message: 'School ID not found' });
        }

        const newNotifications = [];

        // 1. Principal & Org notices and announcements
        try {
            const notices = await Notice.find({
                $or: [{ school: schoolId }, { branch: schoolId }],
                status: { $regex: /^(published|active)$/i }
            }).populate('createdBy', 'name role').lean();

            for (const notice of notices) {
                const creatorId = notice.createdBy?._id || notice.createdBy;
                // Exclude notifications generated by the same logged-in admin
                if (creatorId && creatorId.toString() === userId.toString()) {
                    continue;
                }

                const isPrincipalOrOrg = notice.createdBy?.role === 'principal' || notice.createdBy?.role === 'superadmin' || notice.createdBy?.role === 'admin';
                if (isPrincipalOrOrg) {
                    const title = `Official Notice: ${notice.title}`;
                    const existing = await Notification.findOne({ user: userId, title, message: notice.content });
                    if (!existing) {
                        const senderRole = notice.createdBy?.role === 'superadmin' ? 'Super Admin' : (notice.createdBy?.role === 'principal' ? 'Principal' : 'Admin');
                        newNotifications.push({
                            user: userId,
                            title,
                            message: notice.content,
                            type: 'notice',
                            school: schoolId,
                            senderName: notice.createdBy?.name || senderRole,
                            senderRole: senderRole,
                            source: senderRole,
                            metadata: {
                                senderId: creatorId
                            },
                            createdAt: notice.createdAt || new Date()
                        });
                    }
                }
            }
        } catch (err) {
            console.error("Error syncing notices for admin:", err);
        }

        // 2. Student & Parent support tickets/complaints/requests
        try {
            const tickets = await Ticket.find({ 
                school: schoolId,
                receiverType: { $nin: ["Teacher", "ClassTeacher"] },
                assignedToRole: { $ne: "teacher" }
            }).populate('raisedBy', 'name').lean();
            for (const ticket of tickets) {
                const creatorId = ticket.raisedBy?._id || ticket.raisedBy;
                // Exclude notifications generated by the same logged-in admin
                if (creatorId && creatorId.toString() === userId.toString()) {
                    continue;
                }

                let source = 'System';
                let type = 'notice';

                if (ticket.raisedByRole === 'student') {
                    if (ticket.category === 'complaint') source = 'Student Complaint';
                    else if (ticket.category === 'query') source = 'Student Request';
                    else source = 'Student Ticket';
                } else if (ticket.raisedByRole === 'parent') {
                    if (ticket.category === 'transport') source = 'Parent Transport';
                    else if (ticket.category === 'fee') source = 'Parent Fee Query';
                    else if (ticket.category === 'complaint') source = 'Parent Complaint';
                    else source = 'Parent Query';
                    type = 'fee';
                } else if (ticket.raisedByRole === 'teacher') {
                    source = 'Teacher Support';
                }

                const title = `[${source}] ${ticket.title}`;
                const existing = await Notification.findOne({ user: userId, title, message: ticket.description });
                if (!existing) {
                    newNotifications.push({
                        user: userId,
                        title,
                        message: ticket.description,
                        type: type,
                        school: schoolId,
                        senderName: ticket.raisedBy?.name || 'User',
                        senderRole: ticket.raisedByRole.charAt(0).toUpperCase() + ticket.raisedByRole.slice(1),
                        source: source,
                        metadata: {
                            senderId: creatorId
                        },
                        createdAt: ticket.createdAt || new Date()
                    });
                }
            }
        } catch (err) {
            console.error("Error syncing tickets for admin:", err);
        }

        // 3. Teacher Leave requests
        try {
            const leaves = await StaffLeave.find({ school: schoolId }).populate('staffId', 'name').lean();
            for (const leave of leaves) {
                const creatorId = leave.staffId?._id || leave.staffId;
                // Exclude notifications generated by the same logged-in admin
                if (creatorId && creatorId.toString() === userId.toString()) {
                    continue;
                }

                const title = `Leave Request: ${leave.status.toUpperCase()}`;
                const message = `Leave request submitted by ${leave.staffId?.name || 'Staff'}. Reason: ${leave.reason || 'Not specified'}`;
                const existing = await Notification.findOne({ user: userId, title, message });
                if (!existing) {
                    newNotifications.push({
                        user: userId,
                        title,
                        message,
                        type: 'leave',
                        school: schoolId,
                        senderName: leave.staffId?.name || 'Staff',
                        senderRole: 'Teacher',
                        source: 'Leave Request',
                        metadata: {
                            senderId: creatorId
                        },
                        createdAt: leave.createdAt || new Date()
                    });
                }
            }
        } catch (err) {
            console.error("Error syncing staff leaves for admin:", err);
        }

        // 4. Principal Exams published
        try {
            const exams = await Exam.find({ school: schoolId }).populate('createdBy', 'name').lean();
            for (const exam of exams) {
                const creatorId = exam.createdBy?._id || exam.createdBy;
                // Exclude notifications generated by the same logged-in admin
                if (creatorId && creatorId.toString() === userId.toString()) {
                    continue;
                }

                const title = `Exam Schedule Published`;
                const message = `Exam "${exam.examName}" published for ${exam.className} (Subject: ${exam.subject})`;
                const existing = await Notification.findOne({ user: userId, title, message });
                if (!existing) {
                    newNotifications.push({
                        user: userId,
                        title,
                        message,
                        type: 'event',
                        school: schoolId,
                        senderName: exam.createdBy?.name || 'Principal',
                        senderRole: 'Principal',
                        source: 'Principal',
                        metadata: {
                            senderId: creatorId
                        },
                        createdAt: exam.createdAt || new Date()
                    });
                }
            }
        } catch (err) {
            console.error("Error syncing exams for admin:", err);
        }

        // 5. Admission Requests
        try {
            const admissions = await AdmissionRequest.find({ branch: schoolId }).lean();
            for (const adm of admissions) {
                if (adm.status !== 'pending') {
                    // Clean up / remove any stored notifications for this request since it is no longer pending
                    await Notification.deleteMany({
                        user: userId,
                        "metadata.link": `/admin/admissions/request`,
                        "metadata.messageId": adm._id
                    });
                    continue;
                }

                const studentName = adm.students?.[0]?.fullName || "Student";
                const parentName = adm.parent?.fullName || "Parent";
                
                const title = "New Admission Request";
                const message = `A new admission request has been submitted by ${studentName}.`;

                const existing = await Notification.findOne({
                    user: userId,
                    "metadata.link": `/admin/admissions/request`,
                    "metadata.messageId": adm._id
                });

                if (!existing) {
                    newNotifications.push({
                        user: userId,
                        title,
                        message,
                        type: 'admissions',
                        school: schoolId,
                        senderName: parentName,
                        senderRole: 'Parent',
                        source: 'Admissions',
                        metadata: {
                            link: `/admin/admissions/request`,
                            messageId: adm._id,
                            subject: studentName
                        },
                        createdAt: adm.createdAt || new Date()
                    });
                }
            }
        } catch (err) {
            console.error("Error syncing admission requests for admin:", err);
        }

        // Bulk insert if there are any new notifications
        if (newNotifications.length > 0) {
            await Notification.insertMany(newNotifications);
        }

        // Fetch all notifications for the admin
        let allNotifications = await Notification.find({ user: userId })
            .sort({ createdAt: -1 })
            .lean();

        // Exclude self-notifications generated by the same logged-in admin
        allNotifications = allNotifications.filter(n => {
            const isSelfSenderId = n.metadata?.senderId && n.metadata.senderId.toString() === userId.toString();
            const isSelfAdminRole = (n.senderRole === 'Admin' || n.senderRole === 'Super Admin' || n.source === 'Admin' || n.source === 'Super Admin') &&
                n.senderName?.trim().toLowerCase() === req.user.name?.trim().toLowerCase();
            return !(isSelfSenderId || isSelfAdminRole);
        });

        res.status(200).json({ success: true, data: allNotifications });
    } catch (error) {
        console.error("Error in syncAndGetAdminNotifications:", error);
        res.status(500).json({ success: false, message: error.message });
    }
};

/**
 * @desc    Mark a single notification as read
 * @route   PATCH /api/admin/notifications/:id/read
 * @access  Private (Admin)
 */
export const markAdminNotificationRead = async (req, res) => {
    try {
        const userId = req.user._id;
        const notification = await Notification.findOneAndUpdate(
            { _id: req.params.id, user: userId },
            { read: true },
            { new: true }
        );

        if (!notification) {
            return res.status(404).json({ success: false, message: 'Notification not found' });
        }

        res.status(200).json({ success: true, data: notification });
    } catch (error) {
        res.status(500).json({ success: false, message: error.message });
    }
};

/**
 * @desc    Mark all unread notifications as read
 * @route   POST /api/admin/notifications/mark-all-read
 * @access  Private (Admin)
 */
export const markAllAdminNotificationsRead = async (req, res) => {
    try {
        const userId = req.user._id;
        await Notification.updateMany(
            { user: userId, read: false },
            { read: true }
        );

        res.status(200).json({ success: true, message: 'All notifications marked as read' });
    } catch (error) {
        res.status(500).json({ success: false, message: error.message });
    }
};
